"""The scheduled batch run: detect → group RCA → brief.

``run_batch`` is what ``lens run <config.yaml>`` executes — the "morning
brief" path. It composes the pieces that already exist as libraries:

1. :class:`lens.orchestrator.DetectionOrchestrator` over the configured
   sources (with feedback suppression applied, ADR 0001).
2. One RCA per Finding Group at/above the configured severity floor
   (ADR 0003) — never one per finding, so a fan-out incident costs one LLM
   call, not hundreds. Suppressed findings never trigger RCA.
3. :func:`lens.brief.html.render_brief` → ``brief.{run_id}.html`` plus an
   atomically repointed ``brief.latest.html``, and the markdown digest
   returned for stdout / Slack.

Per-group RCA failures are logged and skipped; the brief still renders.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path

import polars as pl

from lens.brief.html import render_brief
from lens.brief.markdown import render_brief_summary
from lens.feedback_loop import is_suppressed
from lens.orchestrator import DetectionOrchestrator, _atomic_symlink, _materialize_source
from lens.rca.agent import RCAAgent
from lens.run_config import RunConfig
from lens.types import SEVERITY_ORDER, Finding, RCAResult, finding_group_key
from lens.wiki.cache import WikiCache
from lens.wiki.ingest import ClaudeCodeClient, LLMClient

logger = logging.getLogger(__name__)


@dataclass
class BatchResult:
    """Everything one batch run produced."""

    run_id: str
    findings: list[Finding]
    rcas: dict[str, RCAResult] = field(default_factory=dict)
    findings_path: Path | None = None
    brief_html_path: Path | None = None
    markdown_digest: str = ""
    rca_groups_investigated: int = 0
    rca_groups_skipped_below_floor: int = 0
    rca_groups_skipped_over_cap: int = 0


def _build_orchestrator(cfg: RunConfig) -> DetectionOrchestrator:
    orch = DetectionOrchestrator(entity_col=cfg.entity_col, snapshot_col=cfg.snapshot_col)
    for spec in cfg.checks:
        orch.add_single(spec["name"], sources=spec.get("sources"), **spec["params"])
    for spec in cfg.cross_checks:
        orch.add_cross(spec["name"], **spec["params"])
    return orch


def _build_rca_client(cfg: RunConfig, llm_client: LLMClient | None) -> LLMClient | None:
    """Pick the LLM client for RCA.

    An injected client (tests) always wins. Otherwise, when ``rca.model`` is
    set, build a :class:`ClaudeCodeClient` pinned to that model (e.g. a cheaper
    tier) for cost control; else ``None`` lets :class:`RCAAgent` use its
    default client.
    """
    if llm_client is not None:
        return llm_client
    if cfg.rca.model:
        return ClaudeCodeClient(extra_args=["--model", cfg.rca.model])
    return None


def _group_for_rca(findings: list[Finding]) -> dict[tuple[str, str], list[Finding]]:
    """Bucket non-suppressed findings into Finding Groups (ADR 0003)."""
    groups: dict[tuple[str, str], list[Finding]] = {}
    for f in findings:
        if is_suppressed(f):
            continue
        groups.setdefault(finding_group_key(f), []).append(f)
    return groups


def _group_representative(members: list[Finding]) -> Finding:
    """Highest severity, then highest confidence, then stable finding_id."""
    return max(
        members,
        key=lambda f: (
            SEVERITY_ORDER.get(f.issue.severity, -1),
            float(f.issue.confidence or 0.0),
            f.finding_id,
        ),
    )


def _prior_findings_target(output_dir: Path) -> Path | None:
    """Resolve the pre-run ``findings.latest.json`` target for the brief delta.

    Must be captured BEFORE the orchestrator repoints the symlink at the new
    run's file, otherwise the delta compares the run against itself.
    """
    latest = output_dir / "findings.latest.json"
    try:
        return latest.resolve(strict=True) if latest.exists() else None
    except OSError:
        return None


def run_batch(
    cfg: RunConfig,
    *,
    run_id: str | None = None,
    llm_client: LLMClient | None = None,
) -> BatchResult:
    """Execute one full batch run. See module docstring for the shape."""
    cfg.output_dir.mkdir(parents=True, exist_ok=True)
    prior_findings = _prior_findings_target(cfg.output_dir)

    # Materialize sources once; the same LazyFrames feed detection and RCA
    # row sampling.
    lazy_sources: dict[str, pl.LazyFrame] = {
        name: _materialize_source(src) for name, src in cfg.sources.items()
    }

    orch = _build_orchestrator(cfg)
    findings = orch.run(
        sources=dict(lazy_sources),
        wiki_root=cfg.wiki_root,
        output_dir=cfg.output_dir,
        run_id=run_id,
        feedback_path=cfg.feedback.path,
        feedback_expiry_days=cfg.feedback.expiry_days,
    )
    actual_run_id = findings[0].run_id if findings else (run_id or "")
    if not actual_run_id:
        # Empty run with autogenerated id: recover it from the latest symlink.
        latest = cfg.output_dir / "findings.latest.json"
        try:
            target = latest.resolve(strict=True).name
            actual_run_id = target.removeprefix("findings.").removesuffix(".json")
        except OSError:
            actual_run_id = "unknown"

    result = BatchResult(
        run_id=actual_run_id,
        findings=findings,
        findings_path=cfg.output_dir / f"findings.{actual_run_id}.json",
    )

    # --- batch RCA: one investigation per Finding Group (ADR 0003) -------
    if cfg.rca.enabled and findings:
        wiki = WikiCache.from_dir(cfg.wiki_root) if cfg.wiki_root else WikiCache()
        agent = RCAAgent(
            repo_root=cfg.rca.repo_root,
            client=_build_rca_client(cfg, llm_client),
            output_dir=cfg.output_dir,
        )
        floor = SEVERITY_ORDER[cfg.rca.severity_floor]

        # Collect groups above the floor, then keep the most important ones up
        # to `max_investigations` — each investigation is one LLM call, so this
        # bounds worst-case token cost on an incident day.
        eligible: list[tuple[tuple[str, str], list[Finding], Finding]] = []
        for key, members in _group_for_rca(findings).items():
            rep = _group_representative(members)
            if SEVERITY_ORDER.get(rep.issue.severity, -1) < floor:
                result.rca_groups_skipped_below_floor += 1
                continue
            eligible.append((key, members, rep))
        eligible.sort(
            key=lambda t: (
                -SEVERITY_ORDER.get(t[2].issue.severity, -1),
                -float(t[2].issue.confidence or 0.0),
                t[0],
            )
        )
        cap = cfg.rca.max_investigations
        if cap is not None and len(eligible) > cap:
            result.rca_groups_skipped_over_cap = len(eligible) - cap
            eligible = eligible[:cap]

        for key, members, rep in eligible:
            try:
                rca = agent.investigate(
                    rep,
                    wiki,
                    lazy_sources,
                    snapshot_col=cfg.snapshot_col,
                    entity_col=cfg.entity_col,
                    group=members,
                    sample_rows=cfg.rca.sample_rows,
                    max_commits=cfg.rca.max_commits,
                )
                agent.save(rca, actual_run_id)
            except Exception as exc:  # noqa: BLE001 - one bad group must not kill the brief
                logger.exception("batch: RCA failed for group %s: %s", key, exc)
                continue
            result.rca_groups_investigated += 1
            # The group shares one hypothesis — attach it to every member so
            # each brief card can render it.
            for member in members:
                result.rcas[member.finding_id] = rca

    # --- brief ------------------------------------------------------------
    brief_path = cfg.output_dir / f"brief.{actual_run_id}.html"
    render_brief(
        findings,
        result.rcas,
        brief_path,
        prior_findings_path=prior_findings,
        dataset_label=cfg.brief.dataset_label,
    )
    _atomic_symlink(brief_path.name, cfg.output_dir / "brief.latest.html")
    result.brief_html_path = brief_path

    result.markdown_digest = render_brief_summary(
        findings,
        result.rcas,
        top_n=cfg.brief.top_n,
        dataset_label=cfg.brief.dataset_label,
    )
    return result
