"""Local brief server: view the latest brief, capture one-click feedback.

``lens serve`` (or ``python -m lens.brief.serve``) binds a small HTTP server
— stdlib only, loopback by default — that:

* ``GET /`` serves ``brief.latest.html`` from the output directory, re-read
  per request so a cron run that lands mid-session shows up on refresh.
* ``POST /feedback`` accepts the JSON payload the brief's one-click
  ``[real] / [false positive] / [needs more]`` buttons send and appends it to
  ``feedback.jsonl`` via :func:`lens.brief.feedback.append_feedback` (same
  schema as the CLI; safe under concurrent writers).

The brief stays a self-contained static file — opened directly from disk the
buttons degrade gracefully (the page shows the equivalent CLI command).
Analysts on another machine reach the server via SSH port-forward.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

from lens.brief.feedback import append_feedback

logger = logging.getLogger(__name__)

_MAX_BODY_BYTES = 64 * 1024  # feedback payloads are tiny; reject anything big


class BriefServer(ThreadingHTTPServer):
    """ThreadingHTTPServer carrying the brief + feedback paths."""

    daemon_threads = True

    def __init__(
        self,
        server_address: tuple[str, int],
        *,
        brief_path: Path,
        feedback_path: Path,
    ) -> None:
        super().__init__(server_address, _BriefHandler)
        self.brief_path = Path(brief_path)
        self.feedback_path = Path(feedback_path)


# Origin hosts allowed to POST feedback. The server is a loopback tool; a
# same-machine browser tab is the only legitimate caller. Anything else —
# notably a hostile web page POSTing at http://127.0.0.1:8377 from the
# analyst's browser — must not be able to forge suppression votes.
_ALLOWED_ORIGIN_HOSTS = {"localhost", "127.0.0.1", "::1", "[::1]"}


def _origin_host(origin: str) -> str | None:
    """Extract the host part of an Origin header value (no ports)."""
    from urllib.parse import urlsplit

    try:
        host = urlsplit(origin).hostname
    except ValueError:
        return None
    return host


class _BriefHandler(BaseHTTPRequestHandler):
    server: BriefServer  # narrowed for type checkers

    # A stalled client (huge declared Content-Length, body never sent) must
    # not pin a handler thread forever.
    timeout = 30

    # -- helpers ---------------------------------------------------------

    def _send_json(self, status: int, payload: dict[str, Any]) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, format: str, *args: Any) -> None:  # noqa: A002
        logger.info("serve: %s — %s", self.address_string(), format % args)

    # -- routes ----------------------------------------------------------

    def do_GET(self) -> None:  # noqa: N802 - http.server API
        if self.path in ("/", "/index.html", "/brief"):
            try:
                body = self.server.brief_path.read_bytes()
            except OSError:
                self._send_json(
                    404,
                    {
                        "error": f"no brief at {self.server.brief_path}; "
                        "run `lens run <config.yaml>` first"
                    },
                )
                return
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            # The brief is regenerated by cron; never let the browser cache it.
            self.send_header("Cache-Control", "no-store")
            self.end_headers()
            self.wfile.write(body)
            return
        if self.path == "/healthz":
            self._send_json(200, {"ok": True})
            return
        self._send_json(404, {"error": "not found"})

    def do_POST(self) -> None:  # noqa: N802 - http.server API
        if self.path != "/feedback":
            self._send_json(404, {"error": "not found"})
            return

        # CSRF hardening: feedback verdicts drive the suppression loop, so a
        # forged POST can mute real alerts. Requiring application/json blocks
        # no-cors browser POSTs (forms can't send JSON; a cross-origin JSON
        # fetch triggers a preflight this server never approves), and the
        # Origin check rejects anything a browser stamps as non-local.
        content_type = (self.headers.get("Content-Type") or "").split(";", 1)[0].strip()
        if content_type.lower() != "application/json":
            self._send_json(415, {"error": "Content-Type must be application/json"})
            return
        origin = self.headers.get("Origin")
        if origin and _origin_host(origin) not in _ALLOWED_ORIGIN_HOSTS:
            self._send_json(403, {"error": "cross-origin feedback is not accepted"})
            return

        try:
            length = int(self.headers.get("Content-Length") or 0)
        except ValueError:
            self._send_json(400, {"error": "invalid Content-Length"})
            return
        if length <= 0 or length > _MAX_BODY_BYTES:
            self._send_json(400, {"error": "missing or oversized request body"})
            return
        try:
            payload = json.loads(self.rfile.read(length).decode("utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError):
            self._send_json(400, {"error": "body must be JSON"})
            return
        if not isinstance(payload, dict):
            self._send_json(400, {"error": "body must be a JSON object"})
            return

        finding_id = payload.get("finding_id")
        label = payload.get("label")
        if not finding_id or not label:
            self._send_json(400, {"error": "finding_id and label are required"})
            return

        detectors = payload.get("detector_sources")
        if isinstance(detectors, str):
            detectors = [d.strip() for d in detectors.split(",") if d.strip()]

        try:
            entry = append_feedback(
                str(finding_id),
                str(label),
                self.server.feedback_path,
                analyst=payload.get("analyst"),
                note=payload.get("note"),
                entity_id=payload.get("entity_id"),
                field_name=payload.get("field_name"),
                detector_sources=detectors,
            )
        except ValueError as exc:  # unknown label
            self._send_json(400, {"error": str(exc)})
            return
        self._send_json(200, {"ok": True, "entry": entry})


def serve(
    output_dir: Path,
    *,
    host: str = "127.0.0.1",
    port: int = 8377,
    brief_path: Path | None = None,
    feedback_path: Path | None = None,
) -> BriefServer:
    """Build (but don't start) a :class:`BriefServer`. Caller runs serve_forever."""
    output_dir = Path(output_dir)
    return BriefServer(
        (host, port),
        brief_path=brief_path or output_dir / "brief.latest.html",
        feedback_path=feedback_path or output_dir / "feedback.jsonl",
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="lens serve",
        description="Serve the latest LENS brief and capture one-click feedback.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("out"),
        help="Batch output directory holding brief.latest.html (default: ./out).",
    )
    parser.add_argument("--host", default="127.0.0.1", help="Bind host (default: loopback).")
    parser.add_argument("--port", type=int, default=8377, help="Bind port (default: 8377).")
    parser.add_argument(
        "--feedback",
        type=Path,
        default=None,
        help="feedback.jsonl path (default: <output-dir>/feedback.jsonl).",
    )
    args = parser.parse_args(argv)

    server = serve(
        args.output_dir,
        host=args.host,
        port=args.port,
        feedback_path=args.feedback,
    )
    host, port = server.server_address[:2]
    print(f"serving brief at http://{host}:{port}/ (feedback → {server.feedback_path})")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nshutting down")
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":  # pragma: no cover - exercised via CLI
    sys.exit(main())
